---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/mat06156/informatica.klenus.com.br/
    - /bin/rsync -avz --chmod=D755,F644 --exclude '.git*' ./ $DEPLOYPATH
    - find $DEPLOYPATH -type d -exec chmod 755 {} +
    - find $DEPLOYPATH -type f -exec chmod 644 {} +